config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources :users 
  
  resources :events 
    
  resources :comments 
  
  resources :participations
  
  root 'events#index'
  
  get 'users/:id/' => 'users#show', as: 'user_show'
  
  post '/participations/create' => 'participations#create', as: :create_participation

  post '/participations/delete' => 'participations#delete', as: :delete_participation
  
  post 'events/:id/' => 'events#destroy', method: :delete, as: 'delete_event' 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :event


	validates_presence_of :body, :user_id, :event_id
	
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	has_many :participations
	has_many :comments
	has_attached_file :avatar, styles: { medium: "250x250>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	def participants
		self.participations.map do |p|
			User.find(p.user_id)
		end
	end
end

app/models/participation.rb
class Participation < ActiveRecord::Base
	
	validates_uniqueness_of :user_id, :scope => [:event_id]
	belongs_to :user
	belongs_to :event

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :events
	has_many :participations
	has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
		@comments = Comment.all
	end

	def new
		@comment = Comment.new
	end

	def create
		@comment = Comment.new(comment_params)
		if @comment.save
			redirect_to event_path(@comment.event_id)
		else
			render 'new'
		end
	end

	def show
		@comment = Comment.find(params[:id])
	end

	def destroy
		 @comment = Comment.find(params[:id]).destroy
   	redirect_to event_path(@comment)
	end

	


 private

 def comment_params
		params.require(:comment).permit(:body, :event_id, :user_id)
	end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user!, except: :index
	def index
		@events = Event.all
	end
	
	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		if	@event.save
			redirect_to @event
		else
			render 'new'
		end
	end

	def destroy
		 @event = Event.find(params[:id]).destroy
   	redirect_to events_path
	end

	def edit
		if is_author?(params[:id])

			@event = Event.find(params[:id])
		else
			redirect_to events_path notice: "NO"
		end
	end

	def update
    @event = Event.find(params[:id])
     if @event.update(event_params)
    	redirect_to @event
  	else
    	render 'edit'
  end
  end

	def show
		@event = Event.find(params[:id])
		@comments = @event.comments.all
		@comment = @event.comments.build
		@participants = @event.participants
	end


	def participate
		Participation.create(user_id: current_user.id, event_id: params[:id])
		redirect_to participate_event_path(params[:id])
	end

	def destroy_participate
		Participation.destroy(user_id: current_user.id, event_id: params[:id])
		redirect_to participate_event_path(params[:id])
	end
	
	
	def price
		@price = Participation.cost / @event.participations.count
	end


	private
	
	def is_author?(event_id)
		event = Event.find(event_id)
		event.user_id == current_user.id

	end

	def event_params
		params.require(:event).permit(:name, :venue, :description, :address, :hour, :event_date, :places, :user_id, :cost, :avatar)
	end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

 def create
 	participation = Participation.new(user_id: current_user.id, event_id: params[:format])
 	if participation.save
 		redirect_to event_path(participation.event_id)
 	end
 end

 def delete
	participation = current_user.participations.where(event_id: params[:format])
 	if !!participation.delete_all
 		redirect_to event_path(params[:format])
 	end
 end






 private
 	def participation_params
 		params.require(:particpation).permit()
 	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def create
		@post = Post.new
		if @post.save
			redirect_to event_path
		end
	end

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new

	end



	private
		def params_post
			params.require(:post).permit(:name, :content,:event_id, :user_id)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = current_user
	end


	def index
		
	end




end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/comments_helper.rb
module CommentsHelper

	def find_email(user_id)
		User.find(user_id).email
	end

end

app/helpers/events_helper.rb
module EventsHelper

	def find_email(user_id)
		User.find(user_id).email
	end
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_index.html.erb
<div class="comment_all">
	<% @comments.each do |comment| %>
  		<b><%= find_email(comment.user_id) %>:</b>
    	<br />
    	<p><%= comment.body %></p>
    	<p><%= time_ago_in_words(comment.created_at)%></p>
    	<p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
    	<hr/>
	<% end %>
</div>

app/views/comments/_new.html.erb
<div class= "new_comment">

<%= form_for @comment do |f| %>
	
	<div class="field">
	  <%= f.label 'commentaire' %>
   <%= f.text_area :body, size: "20x10" %>
	</div>

	<div class="actions">
	  <%= f.submit 'Poster un commentaire' %>
	</div>

	<%= f.hidden_field :user_id, :value => current_user.id %>

	<%= f.hidden_field :event_id %>

<% end %>
</div>

app/views/comments/show.html.erb
<div class="field">
   <%= @comment.name %>
  </div>

  <div class="field">
		<%= @comment.body %>
	</div>

app/views/events/_form.html.erb
<div class= "connecter">
	<h2>Créer un événement</h2>
<%= form_for @event, html: {multipart: :true} do |e| %>
	<div class="field">
		<%= e.label :name %>
		<%= e.text_field :name %>
	</div>

	<div class="field">
		<%= e.label :avatar %>
		<%= e.file_field :avatar%>
	</div>

	<div class="field">
		<%= e.label :venue %>
		<%= e.text_field :venue %>
	</div>

	<div class="field">
		<%= e.label :description %>
		<%= e.text_area :description %>
	</div>

	<div class="field">
		<%= e.label :address %>
		<%= e.text_field :address %>
	</div>

	<div class="field">
		<%= e.label :event_date %>
		<%= e.date_field :event_date %>
	</div>

	<div class="field">
		<%= e.label :hour %>
		<%= e.text_field :hour %>
	</div>

	<div class="field">
		<%= e.label :places %>
		<%= e.text_field :places %>
	</div>

	<div class="field">
		<%= e.label :cost %>
		<%= e.text_field :cost %>
	</div>


	<%= e.hidden_field :user_id, :value => current_user.id %>

	<div class= "button">
		<%= e.submit "Créer un event" %>
	</div>

<% end %>
</div>

app/views/events/edit.html.erb
<div class= "connecter">
	<h2>Créer un événement</h2>
<%= form_for @event, html: {multipart: :true} do |e| %>
	<div class="field">
		<%= e.label :name %>
		<%= e.text_field :name %>
	</div>

	<div class="field">
		<%= e.label 'Change you image' %>
		<%= e.file_field :avatar%>
	</div>

	<div class="field">
		<%= e.label :venue %>
		<%= e.text_field :venue %>
	</div>

	<div class="field">
		<%= e.label :description %>
		<%= e.text_area :description %>
	</div>

	<div class="field">
		<%= e.label :address %>
		<%= e.text_field :address %>
	</div>

	<div class="field">
		<%= e.label :event_date %>
		<%= e.date_field :event_date %>
	</div>

	<div class="field">
		<%= e.label :hour %>
		<%= e.text_field :hour %>
	</div>

	<div class="field">
		<%= e.label :places %>
		<%= e.text_field :places %>
	</div>

	<div class="field">
		<%= e.label :cost %>
		<%= e.text_field :cost %>
	</div>


	<%= e.hidden_field :user_id, :value => current_user.id %>

	<div class= "button">
		<%= e.submit "Editer" %>
	</div>

<% end %>
</div>

app/views/events/index.html.erb
<div class="content">
	<% @events.each do |e| %>
		<div class="event">
			<h3><%= e.name %></h3>
			<div class="desciption">
					<p><%= e.description %></p>
			</div>
				
			<div>
					Adresse: <b><%= e.address %></b> | <%= e.venue %>
			</div>
				<div class="datetime">
						<% if e.event_date.blank? %>
							<%= "Date non déterminé" %>
						<% else %>
							<%= e.event_date.strftime("%d/%m/%Y") %> |
							<%= e.hour %>
					<% end %>	
				</div>
				<div class="">
					Participant(s): <b> <%= e.participations.count %> / <%= e.places %></b>
				</div>
				<div class="details">
					<%= link_to 'Détails', event_path(e) %>
				</div>

	</div>

<% end %>
</div>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
<div class ="row">
	<div class ="event_title ">
		<h3><%= @event.name %></h3>
	</div>
</div>
<div class="row">
	<div class =" event_left small-3 columns">
		<div>
			<h5>
				Organisateur:<%= find_email(@event.user_id) %> 
			</h5>
			<h5>
				<% if @event.event_date.blank? %>
						<%= "Date non déterminé" %>
				<% else %>
						Date:<%= @event.event_date.strftime("%d/%m/%Y") %> | Heure: <%= @event.hour %>
				<% end %>
			</h5>
			<h5>Adresse:<%= @event.address %></h5>
			<h5>Lieu:<%= @event.venue %></h5>

			<h5>Participants: <%= @event.participations.count %> / <%= @event.places %></h5>
		</div>
	</div>
	
	<div class ="event_center small-6 columns">

		<div class ="imag_show">
			<%= image_tag @event.avatar.url(:medium) %>
		</div>


		<h5>Description:</h5>
		<p>
			<%= @event.description %>
			Nec minus feminae quoque calamitatum participes fuere similium. nam ex hoc quoque sexu peremptae sunt originis altae conplures, adulteriorum flagitiis obnoxiae vel stuprorum. inter quas notiores fuere Claritas et Flaviana, quarum altera cum duceretur ad mortem, indumento, quo vestita erat, abrepto, ne velemen quidem secreto membrorum sufficiens retinere permissa est. ideoque carnifex nefas admisisse convictus inmane, vivus exustus est.
		</p>
	</div>
	
	<div class="event_right small-3 columns">
		<h5>Participation: <%= @event.cost %>€</h5>
		<% if current_user.participations.where(event_id: @event.id) != [] %>
		<h5><%= link_to 'je ne Participe plus', delete_participation_path(@event.id), method: :post %></h5>
		<%else%>
		<h5><%= link_to 'Participer', create_participation_path(@event.id), method: :post %></h5>
		<% end %>

		<h5><%= link_to 'Effacer soirée', delete_event_path, method: :delete %></h5>

		<% if current_user.id == @event.user_id %>
		<h5><%= link_to 'Editer un évenement', edit_event_path %></h5>
		<% else %>
				
		<% end %>

		<%= render 'comments/new' %>

		<%= render 'comments/index'%>

  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">G.Y.P</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
  <% if user_signed_in? %>
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#"><%= link_to 'Créer un événement', new_event_path, method: :get  %></a></li>
      <li class="has-dropdown">
        <a href="#"></a>
        <ul class="">
          <li><%= link_to 'Editer mon profil', edit_event_path(current_user)  %></li>
          <li class="active"><%= link_to 'deconnexion', destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><a href="#">A propos</a></li>
    </ul>

    <% else %>

    <ul class="right">
      <li class="_active"><%= link_to 'Créer un événement', new_event_path, method: :get  %></li>
      <li class="has-dropdown">
        <a href="#"></a>
        <ul class="_dropdown">
          <li><%= link_to 'Inscription', new_user_registration_path %></li>
          <li class="active"><%= link_to 'Connexion', new_user_session_path %></li>
        </ul>
      </li>
    </ul>

    <% end %>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    


    <%= yield %>

  </body>
</html>

app/views/participations/new.html.erb
<%= @user.first_name %>
<%= 

app/views/users/show.html.erb
show.html.erb